# Generated by Django 4.2.21 on 2025-05-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageprovider',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storageprovider',
            name='status',
            field=models.CharField(default='available', max_length=20),
        ),
    ]
