# Generated by Django 4.2.20 on 2025-05-13 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_message_product_alter_message_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('dm', 'DM'), ('comment', 'Comment')], max_length=20),
        ),
    ]
