# Generated by Django 4.2.20 on 2025-05-13 23:25
from django.db import migrations, models  # ✅ Make sure this line exists


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_alter_message_message_type'),
    ]

    operations = [
          migrations.AlterField(
        model_name='message',
        name='message_type',
        field=models.CharField(
            max_length=20,
            choices=[('text', 'Text'), ('dm', 'DM'), ('comment', 'Comment')]
        ),
    ),
    ]
