# Generated by Django 4.2.20 on 2025-05-15 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_auto_20250514_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('dm', 'DM'), ('comment', 'Comment')], max_length=20),
        ),
    ]
